// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "simulationFormat.h"

// int_3d
// 

const int_3d::x_type& int_3d::
x () const
{
  return this->x_.get ();
}

int_3d::x_type& int_3d::
x ()
{
  return this->x_.get ();
}

void int_3d::
x (const x_type& x)
{
  this->x_.set (x);
}

const int_3d::y_type& int_3d::
y () const
{
  return this->y_.get ();
}

int_3d::y_type& int_3d::
y ()
{
  return this->y_.get ();
}

void int_3d::
y (const y_type& x)
{
  this->y_.set (x);
}

const int_3d::z_type& int_3d::
z () const
{
  return this->z_.get ();
}

int_3d::z_type& int_3d::
z ()
{
  return this->z_.get ();
}

void int_3d::
z (const z_type& x)
{
  this->z_.set (x);
}


// double_3d
// 

const double_3d::x_type& double_3d::
x () const
{
  return this->x_.get ();
}

double_3d::x_type& double_3d::
x ()
{
  return this->x_.get ();
}

void double_3d::
x (const x_type& x)
{
  this->x_.set (x);
}

const double_3d::y_type& double_3d::
y () const
{
  return this->y_.get ();
}

double_3d::y_type& double_3d::
y ()
{
  return this->y_.get ();
}

void double_3d::
y (const y_type& x)
{
  this->y_.set (x);
}

const double_3d::z_type& double_3d::
z () const
{
  return this->z_.get ();
}

double_3d::z_type& double_3d::
z ()
{
  return this->z_.get ();
}

void double_3d::
z (const z_type& x)
{
  this->z_.set (x);
}


// log_level
// 


// lennardJones_t
// 

const lennardJones_t::Epsilon_type& lennardJones_t::
Epsilon () const
{
  return this->Epsilon_.get ();
}

lennardJones_t::Epsilon_type& lennardJones_t::
Epsilon ()
{
  return this->Epsilon_.get ();
}

void lennardJones_t::
Epsilon (const Epsilon_type& x)
{
  this->Epsilon_.set (x);
}

const lennardJones_t::Sigma_type& lennardJones_t::
Sigma () const
{
  return this->Sigma_.get ();
}

lennardJones_t::Sigma_type& lennardJones_t::
Sigma ()
{
  return this->Sigma_.get ();
}

void lennardJones_t::
Sigma (const Sigma_type& x)
{
  this->Sigma_.set (x);
}


// ForceType
// 

const ForceType::lennard_optional& ForceType::
lennard () const
{
  return this->lennard_;
}

ForceType::lennard_optional& ForceType::
lennard ()
{
  return this->lennard_;
}

void ForceType::
lennard (const lennard_type& x)
{
  this->lennard_.set (x);
}

void ForceType::
lennard (const lennard_optional& x)
{
  this->lennard_ = x;
}

void ForceType::
lennard (::std::unique_ptr< lennard_type > x)
{
  this->lennard_.set (std::move (x));
}

const ForceType::grav_optional& ForceType::
grav () const
{
  return this->grav_;
}

ForceType::grav_optional& ForceType::
grav ()
{
  return this->grav_;
}

void ForceType::
grav (const grav_type& x)
{
  this->grav_.set (x);
}

void ForceType::
grav (const grav_optional& x)
{
  this->grav_ = x;
}

void ForceType::
grav (::std::unique_ptr< grav_type > x)
{
  this->grav_.set (std::move (x));
}


// Cuboid
// 

const Cuboid::lower_left_coord_type& Cuboid::
lower_left_coord () const
{
  return this->lower_left_coord_.get ();
}

Cuboid::lower_left_coord_type& Cuboid::
lower_left_coord ()
{
  return this->lower_left_coord_.get ();
}

void Cuboid::
lower_left_coord (const lower_left_coord_type& x)
{
  this->lower_left_coord_.set (x);
}

void Cuboid::
lower_left_coord (::std::unique_ptr< lower_left_coord_type > x)
{
  this->lower_left_coord_.set (std::move (x));
}

const Cuboid::number_of_particles_type& Cuboid::
number_of_particles () const
{
  return this->number_of_particles_.get ();
}

Cuboid::number_of_particles_type& Cuboid::
number_of_particles ()
{
  return this->number_of_particles_.get ();
}

void Cuboid::
number_of_particles (const number_of_particles_type& x)
{
  this->number_of_particles_.set (x);
}

void Cuboid::
number_of_particles (::std::unique_ptr< number_of_particles_type > x)
{
  this->number_of_particles_.set (std::move (x));
}

const Cuboid::distance_type& Cuboid::
distance () const
{
  return this->distance_.get ();
}

Cuboid::distance_type& Cuboid::
distance ()
{
  return this->distance_.get ();
}

void Cuboid::
distance (const distance_type& x)
{
  this->distance_.set (x);
}

const Cuboid::mass_type& Cuboid::
mass () const
{
  return this->mass_.get ();
}

Cuboid::mass_type& Cuboid::
mass ()
{
  return this->mass_.get ();
}

void Cuboid::
mass (const mass_type& x)
{
  this->mass_.set (x);
}

const Cuboid::initial_velocity_type& Cuboid::
initial_velocity () const
{
  return this->initial_velocity_.get ();
}

Cuboid::initial_velocity_type& Cuboid::
initial_velocity ()
{
  return this->initial_velocity_.get ();
}

void Cuboid::
initial_velocity (const initial_velocity_type& x)
{
  this->initial_velocity_.set (x);
}

void Cuboid::
initial_velocity (::std::unique_ptr< initial_velocity_type > x)
{
  this->initial_velocity_.set (std::move (x));
}


// Simulation_t
// 

const Simulation_t::t_end_optional& Simulation_t::
t_end () const
{
  return this->t_end_;
}

Simulation_t::t_end_optional& Simulation_t::
t_end ()
{
  return this->t_end_;
}

void Simulation_t::
t_end (const t_end_type& x)
{
  this->t_end_.set (x);
}

void Simulation_t::
t_end (const t_end_optional& x)
{
  this->t_end_ = x;
}

Simulation_t::t_end_type Simulation_t::
t_end_default_value ()
{
  return t_end_type (5.0);
}

const Simulation_t::delta_t_optional& Simulation_t::
delta_t () const
{
  return this->delta_t_;
}

Simulation_t::delta_t_optional& Simulation_t::
delta_t ()
{
  return this->delta_t_;
}

void Simulation_t::
delta_t (const delta_t_type& x)
{
  this->delta_t_.set (x);
}

void Simulation_t::
delta_t (const delta_t_optional& x)
{
  this->delta_t_ = x;
}

Simulation_t::delta_t_type Simulation_t::
delta_t_default_value ()
{
  return delta_t_type (.0002);
}

const Simulation_t::force_optional& Simulation_t::
force () const
{
  return this->force_;
}

Simulation_t::force_optional& Simulation_t::
force ()
{
  return this->force_;
}

void Simulation_t::
force (const force_type& x)
{
  this->force_.set (x);
}

void Simulation_t::
force (const force_optional& x)
{
  this->force_ = x;
}

void Simulation_t::
force (::std::unique_ptr< force_type > x)
{
  this->force_.set (std::move (x));
}

const Simulation_t::averageVelo_optional& Simulation_t::
averageVelo () const
{
  return this->averageVelo_;
}

Simulation_t::averageVelo_optional& Simulation_t::
averageVelo ()
{
  return this->averageVelo_;
}

void Simulation_t::
averageVelo (const averageVelo_type& x)
{
  this->averageVelo_.set (x);
}

void Simulation_t::
averageVelo (const averageVelo_optional& x)
{
  this->averageVelo_ = x;
}

Simulation_t::averageVelo_type Simulation_t::
averageVelo_default_value ()
{
  return averageVelo_type (.1);
}

const Simulation_t::cuboid_sequence& Simulation_t::
cuboid () const
{
  return this->cuboid_;
}

Simulation_t::cuboid_sequence& Simulation_t::
cuboid ()
{
  return this->cuboid_;
}

void Simulation_t::
cuboid (const cuboid_sequence& s)
{
  this->cuboid_ = s;
}

const Simulation_t::base_name_optional& Simulation_t::
base_name () const
{
  return this->base_name_;
}

Simulation_t::base_name_optional& Simulation_t::
base_name ()
{
  return this->base_name_;
}

void Simulation_t::
base_name (const base_name_type& x)
{
  this->base_name_.set (x);
}

void Simulation_t::
base_name (const base_name_optional& x)
{
  this->base_name_ = x;
}

void Simulation_t::
base_name (::std::unique_ptr< base_name_type > x)
{
  this->base_name_.set (std::move (x));
}

const Simulation_t::base_name_type& Simulation_t::
base_name_default_value ()
{
  return base_name_default_value_;
}

const Simulation_t::writeFrequency_optional& Simulation_t::
writeFrequency () const
{
  return this->writeFrequency_;
}

Simulation_t::writeFrequency_optional& Simulation_t::
writeFrequency ()
{
  return this->writeFrequency_;
}

void Simulation_t::
writeFrequency (const writeFrequency_type& x)
{
  this->writeFrequency_.set (x);
}

void Simulation_t::
writeFrequency (const writeFrequency_optional& x)
{
  this->writeFrequency_ = x;
}

const Simulation_t::log_level_optional& Simulation_t::
log_level () const
{
  return this->log_level_;
}

Simulation_t::log_level_optional& Simulation_t::
log_level ()
{
  return this->log_level_;
}

void Simulation_t::
log_level (const log_level_type& x)
{
  this->log_level_.set (x);
}

void Simulation_t::
log_level (const log_level_optional& x)
{
  this->log_level_ = x;
}

void Simulation_t::
log_level (::std::unique_ptr< log_level_type > x)
{
  this->log_level_.set (std::move (x));
}

Simulation_t::log_level_type Simulation_t::
log_level_default_value ()
{
  return log_level_type (2LL);
}

const Simulation_t::testing_mode_optional& Simulation_t::
testing_mode () const
{
  return this->testing_mode_;
}

Simulation_t::testing_mode_optional& Simulation_t::
testing_mode ()
{
  return this->testing_mode_;
}

void Simulation_t::
testing_mode (const testing_mode_type& x)
{
  this->testing_mode_.set (x);
}

void Simulation_t::
testing_mode (const testing_mode_optional& x)
{
  this->testing_mode_ = x;
}

Simulation_t::testing_mode_type Simulation_t::
testing_mode_default_value ()
{
  return testing_mode_type (false);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// int_3d
//

int_3d::
int_3d (const x_type& x,
        const y_type& y,
        const z_type& z)
: ::xml_schema::type (),
  x_ (x, this),
  y_ (y, this),
  z_ (z, this)
{
}

int_3d::
int_3d (const int_3d& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_ (x.x_, f, this),
  y_ (x.y_, f, this),
  z_ (x.z_, f, this)
{
}

int_3d::
int_3d (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_ (this),
  y_ (this),
  z_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void int_3d::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x
    //
    if (n.name () == "x" && n.namespace_ ().empty ())
    {
      if (!x_.present ())
      {
        this->x_.set (x_traits::create (i, f, this));
        continue;
      }
    }

    // y
    //
    if (n.name () == "y" && n.namespace_ ().empty ())
    {
      if (!y_.present ())
      {
        this->y_.set (y_traits::create (i, f, this));
        continue;
      }
    }

    // z
    //
    if (n.name () == "z" && n.namespace_ ().empty ())
    {
      if (!z_.present ())
      {
        this->z_.set (z_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x",
      "");
  }

  if (!y_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y",
      "");
  }

  if (!z_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z",
      "");
  }
}

int_3d* int_3d::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class int_3d (*this, f, c);
}

int_3d& int_3d::
operator= (const int_3d& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_ = x.x_;
    this->y_ = x.y_;
    this->z_ = x.z_;
  }

  return *this;
}

int_3d::
~int_3d ()
{
}

// double_3d
//

double_3d::
double_3d (const x_type& x,
           const y_type& y,
           const z_type& z)
: ::xml_schema::type (),
  x_ (x, this),
  y_ (y, this),
  z_ (z, this)
{
}

double_3d::
double_3d (const double_3d& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_ (x.x_, f, this),
  y_ (x.y_, f, this),
  z_ (x.z_, f, this)
{
}

double_3d::
double_3d (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_ (this),
  y_ (this),
  z_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void double_3d::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x
    //
    if (n.name () == "x" && n.namespace_ ().empty ())
    {
      if (!x_.present ())
      {
        this->x_.set (x_traits::create (i, f, this));
        continue;
      }
    }

    // y
    //
    if (n.name () == "y" && n.namespace_ ().empty ())
    {
      if (!y_.present ())
      {
        this->y_.set (y_traits::create (i, f, this));
        continue;
      }
    }

    // z
    //
    if (n.name () == "z" && n.namespace_ ().empty ())
    {
      if (!z_.present ())
      {
        this->z_.set (z_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x",
      "");
  }

  if (!y_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y",
      "");
  }

  if (!z_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z",
      "");
  }
}

double_3d* double_3d::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class double_3d (*this, f, c);
}

double_3d& double_3d::
operator= (const double_3d& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_ = x.x_;
    this->y_ = x.y_;
    this->z_ = x.z_;
  }

  return *this;
}

double_3d::
~double_3d ()
{
}

// log_level
//

log_level::
log_level (const ::xml_schema::integer& _xsd_integer_base)
: ::xsd::cxx::tree::fundamental_base< ::xml_schema::integer, char, ::xml_schema::simple_type > (_xsd_integer_base)
{
}

log_level::
log_level (const log_level& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xsd::cxx::tree::fundamental_base< ::xml_schema::integer, char, ::xml_schema::simple_type > (x, f, c)
{
}

log_level::
log_level (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xsd::cxx::tree::fundamental_base< ::xml_schema::integer, char, ::xml_schema::simple_type > (e, f, c)
{
}

log_level::
log_level (const ::xercesc::DOMAttr& a,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xsd::cxx::tree::fundamental_base< ::xml_schema::integer, char, ::xml_schema::simple_type > (a, f, c)
{
}

log_level::
log_level (const ::std::string& s,
           const ::xercesc::DOMElement* e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xsd::cxx::tree::fundamental_base< ::xml_schema::integer, char, ::xml_schema::simple_type > (s, e, f, c)
{
}

log_level* log_level::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class log_level (*this, f, c);
}

log_level::
~log_level ()
{
}

// lennardJones_t
//

lennardJones_t::
lennardJones_t (const Epsilon_type& Epsilon,
                const Sigma_type& Sigma)
: ::xml_schema::type (),
  Epsilon_ (Epsilon, this),
  Sigma_ (Sigma, this)
{
}

lennardJones_t::
lennardJones_t (const lennardJones_t& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  Epsilon_ (x.Epsilon_, f, this),
  Sigma_ (x.Sigma_, f, this)
{
}

lennardJones_t::
lennardJones_t (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  Epsilon_ (this),
  Sigma_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void lennardJones_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Epsilon
    //
    if (n.name () == "Epsilon" && n.namespace_ ().empty ())
    {
      if (!Epsilon_.present ())
      {
        this->Epsilon_.set (Epsilon_traits::create (i, f, this));
        continue;
      }
    }

    // Sigma
    //
    if (n.name () == "Sigma" && n.namespace_ ().empty ())
    {
      if (!Sigma_.present ())
      {
        this->Sigma_.set (Sigma_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!Epsilon_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Epsilon",
      "");
  }

  if (!Sigma_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Sigma",
      "");
  }
}

lennardJones_t* lennardJones_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class lennardJones_t (*this, f, c);
}

lennardJones_t& lennardJones_t::
operator= (const lennardJones_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->Epsilon_ = x.Epsilon_;
    this->Sigma_ = x.Sigma_;
  }

  return *this;
}

lennardJones_t::
~lennardJones_t ()
{
}

// ForceType
//

ForceType::
ForceType ()
: ::xml_schema::type (),
  lennard_ (this),
  grav_ (this)
{
}

ForceType::
ForceType (const ForceType& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  lennard_ (x.lennard_, f, this),
  grav_ (x.grav_, f, this)
{
}

ForceType::
ForceType (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  lennard_ (this),
  grav_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void ForceType::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // lennard
    //
    if (n.name () == "lennard" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< lennard_type > r (
        lennard_traits::create (i, f, this));

      if (!this->lennard_)
      {
        this->lennard_.set (::std::move (r));
        continue;
      }
    }

    // grav
    //
    if (n.name () == "grav" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< grav_type > r (
        grav_traits::create (i, f, this));

      if (!this->grav_)
      {
        this->grav_.set (::std::move (r));
        continue;
      }
    }

    break;
  }
}

ForceType* ForceType::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class ForceType (*this, f, c);
}

ForceType& ForceType::
operator= (const ForceType& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->lennard_ = x.lennard_;
    this->grav_ = x.grav_;
  }

  return *this;
}

ForceType::
~ForceType ()
{
}

// Cuboid
//

Cuboid::
Cuboid (const lower_left_coord_type& lower_left_coord,
        const number_of_particles_type& number_of_particles,
        const distance_type& distance,
        const mass_type& mass,
        const initial_velocity_type& initial_velocity)
: ::xml_schema::type (),
  lower_left_coord_ (lower_left_coord, this),
  number_of_particles_ (number_of_particles, this),
  distance_ (distance, this),
  mass_ (mass, this),
  initial_velocity_ (initial_velocity, this)
{
}

Cuboid::
Cuboid (::std::unique_ptr< lower_left_coord_type > lower_left_coord,
        ::std::unique_ptr< number_of_particles_type > number_of_particles,
        const distance_type& distance,
        const mass_type& mass,
        ::std::unique_ptr< initial_velocity_type > initial_velocity)
: ::xml_schema::type (),
  lower_left_coord_ (std::move (lower_left_coord), this),
  number_of_particles_ (std::move (number_of_particles), this),
  distance_ (distance, this),
  mass_ (mass, this),
  initial_velocity_ (std::move (initial_velocity), this)
{
}

Cuboid::
Cuboid (const Cuboid& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  lower_left_coord_ (x.lower_left_coord_, f, this),
  number_of_particles_ (x.number_of_particles_, f, this),
  distance_ (x.distance_, f, this),
  mass_ (x.mass_, f, this),
  initial_velocity_ (x.initial_velocity_, f, this)
{
}

Cuboid::
Cuboid (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  lower_left_coord_ (this),
  number_of_particles_ (this),
  distance_ (this),
  mass_ (this),
  initial_velocity_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Cuboid::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // lower-left-coord
    //
    if (n.name () == "lower-left-coord" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< lower_left_coord_type > r (
        lower_left_coord_traits::create (i, f, this));

      if (!lower_left_coord_.present ())
      {
        this->lower_left_coord_.set (::std::move (r));
        continue;
      }
    }

    // number-of-particles
    //
    if (n.name () == "number-of-particles" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< number_of_particles_type > r (
        number_of_particles_traits::create (i, f, this));

      if (!number_of_particles_.present ())
      {
        this->number_of_particles_.set (::std::move (r));
        continue;
      }
    }

    // distance
    //
    if (n.name () == "distance" && n.namespace_ ().empty ())
    {
      if (!distance_.present ())
      {
        this->distance_.set (distance_traits::create (i, f, this));
        continue;
      }
    }

    // mass
    //
    if (n.name () == "mass" && n.namespace_ ().empty ())
    {
      if (!mass_.present ())
      {
        this->mass_.set (mass_traits::create (i, f, this));
        continue;
      }
    }

    // initial_velocity
    //
    if (n.name () == "initial_velocity" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< initial_velocity_type > r (
        initial_velocity_traits::create (i, f, this));

      if (!initial_velocity_.present ())
      {
        this->initial_velocity_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!lower_left_coord_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "lower-left-coord",
      "");
  }

  if (!number_of_particles_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "number-of-particles",
      "");
  }

  if (!distance_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "distance",
      "");
  }

  if (!mass_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "mass",
      "");
  }

  if (!initial_velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "initial_velocity",
      "");
  }
}

Cuboid* Cuboid::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Cuboid (*this, f, c);
}

Cuboid& Cuboid::
operator= (const Cuboid& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->lower_left_coord_ = x.lower_left_coord_;
    this->number_of_particles_ = x.number_of_particles_;
    this->distance_ = x.distance_;
    this->mass_ = x.mass_;
    this->initial_velocity_ = x.initial_velocity_;
  }

  return *this;
}

Cuboid::
~Cuboid ()
{
}

// Simulation_t
//

const Simulation_t::base_name_type Simulation_t::base_name_default_value_ (
  "MD_vtk");

Simulation_t::
Simulation_t ()
: ::xml_schema::type (),
  t_end_ (this),
  delta_t_ (this),
  force_ (this),
  averageVelo_ (this),
  cuboid_ (this),
  base_name_ (this),
  writeFrequency_ (this),
  log_level_ (this),
  testing_mode_ (this)
{
}

Simulation_t::
Simulation_t (const Simulation_t& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  t_end_ (x.t_end_, f, this),
  delta_t_ (x.delta_t_, f, this),
  force_ (x.force_, f, this),
  averageVelo_ (x.averageVelo_, f, this),
  cuboid_ (x.cuboid_, f, this),
  base_name_ (x.base_name_, f, this),
  writeFrequency_ (x.writeFrequency_, f, this),
  log_level_ (x.log_level_, f, this),
  testing_mode_ (x.testing_mode_, f, this)
{
}

Simulation_t::
Simulation_t (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  t_end_ (this),
  delta_t_ (this),
  force_ (this),
  averageVelo_ (this),
  cuboid_ (this),
  base_name_ (this),
  writeFrequency_ (this),
  log_level_ (this),
  testing_mode_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Simulation_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // t_end
    //
    if (n.name () == "t_end" && n.namespace_ ().empty ())
    {
      if (!this->t_end_)
      {
        this->t_end_.set (t_end_traits::create (i, f, this));
        continue;
      }
    }

    // delta_t
    //
    if (n.name () == "delta_t" && n.namespace_ ().empty ())
    {
      if (!this->delta_t_)
      {
        this->delta_t_.set (delta_t_traits::create (i, f, this));
        continue;
      }
    }

    // force
    //
    if (n.name () == "force" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< force_type > r (
        force_traits::create (i, f, this));

      if (!this->force_)
      {
        this->force_.set (::std::move (r));
        continue;
      }
    }

    // averageVelo
    //
    if (n.name () == "averageVelo" && n.namespace_ ().empty ())
    {
      if (!this->averageVelo_)
      {
        this->averageVelo_.set (averageVelo_traits::create (i, f, this));
        continue;
      }
    }

    // cuboid
    //
    if (n.name () == "cuboid" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< cuboid_type > r (
        cuboid_traits::create (i, f, this));

      this->cuboid_.push_back (::std::move (r));
      continue;
    }

    // base_name
    //
    if (n.name () == "base_name" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< base_name_type > r (
        base_name_traits::create (i, f, this));

      if (!this->base_name_)
      {
        this->base_name_.set (::std::move (r));
        continue;
      }
    }

    // writeFrequency
    //
    if (n.name () == "writeFrequency" && n.namespace_ ().empty ())
    {
      if (!this->writeFrequency_)
      {
        this->writeFrequency_.set (writeFrequency_traits::create (i, f, this));
        continue;
      }
    }

    // log_level
    //
    if (n.name () == "log_level" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< log_level_type > r (
        log_level_traits::create (i, f, this));

      if (!this->log_level_)
      {
        this->log_level_.set (::std::move (r));
        continue;
      }
    }

    // testing_mode
    //
    if (n.name () == "testing_mode" && n.namespace_ ().empty ())
    {
      if (!this->testing_mode_)
      {
        this->testing_mode_.set (testing_mode_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }
}

Simulation_t* Simulation_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Simulation_t (*this, f, c);
}

Simulation_t& Simulation_t::
operator= (const Simulation_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->t_end_ = x.t_end_;
    this->delta_t_ = x.delta_t_;
    this->force_ = x.force_;
    this->averageVelo_ = x.averageVelo_;
    this->cuboid_ = x.cuboid_;
    this->base_name_ = x.base_name_;
    this->writeFrequency_ = x.writeFrequency_;
    this->log_level_ = x.log_level_;
    this->testing_mode_ = x.testing_mode_;
  }

  return *this;
}

Simulation_t::
~Simulation_t ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::Simulation_t >
Simulation (const ::std::string& u,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Simulation_t > (
    ::Simulation (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Simulation_t >
Simulation (const ::std::string& u,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Simulation_t > (
    ::Simulation (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Simulation_t >
Simulation (const ::std::string& u,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Simulation_t > (
    ::Simulation (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Simulation_t >
Simulation (::std::istream& is,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Simulation (isrc, f, p);
}

::std::unique_ptr< ::Simulation_t >
Simulation (::std::istream& is,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Simulation (isrc, h, f, p);
}

::std::unique_ptr< ::Simulation_t >
Simulation (::std::istream& is,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Simulation (isrc, h, f, p);
}

::std::unique_ptr< ::Simulation_t >
Simulation (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Simulation (isrc, f, p);
}

::std::unique_ptr< ::Simulation_t >
Simulation (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Simulation (isrc, h, f, p);
}

::std::unique_ptr< ::Simulation_t >
Simulation (::std::istream& is,
            const ::std::string& sid,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Simulation (isrc, h, f, p);
}

::std::unique_ptr< ::Simulation_t >
Simulation (::xercesc::InputSource& i,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Simulation_t > (
    ::Simulation (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Simulation_t >
Simulation (::xercesc::InputSource& i,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Simulation_t > (
    ::Simulation (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Simulation_t >
Simulation (::xercesc::InputSource& i,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Simulation_t > (
    ::Simulation (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Simulation_t >
Simulation (const ::xercesc::DOMDocument& doc,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::Simulation_t > (
      ::Simulation (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Simulation" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Simulation_t > r (
      ::xsd::cxx::tree::traits< ::Simulation_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Simulation",
    "");
}

::std::unique_ptr< ::Simulation_t >
Simulation (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
            ::xml_schema::flags f,
            const ::xml_schema::properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "Simulation" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Simulation_t > r (
      ::xsd::cxx::tree::traits< ::Simulation_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Simulation",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

