//
// Created by rodff on 14.01.24.
//

#ifndef PSEMOLDYN_GROUPD_PARALLELIZATIONSTRATEGY_H
#define PSEMOLDYN_GROUPD_PARALLELIZATIONSTRATEGY_H

enum ParallelizationStrategy {
    SUBDOMAIN,
    CELL,
    NONE
};

#endif //PSEMOLDYN_GROUPD_PARALLELIZATIONSTRATEGY_H
