name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main 

permissions:
        contents: write 
        pages: write
        id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: Generate Doxygen documentation
      run: |
        doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3

      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: documentation/html
